<?php

/**
 * @file
 * Contains related_articles.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function related_articles_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the related_articles module.
    case 'help.page.related_articles':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for show related articles') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function related_articles_theme() {
  return [
    'related_articles_block' => [
      'variables' => [
        'articles' => NULL,
      ],
    ],
  ];
}
