<?php

/**
 * @file
 * Contains subscribe_mailchimp.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function subscribe_mailchimp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the subscribe_mailchimp module.
    case 'help.page.subscribe_mailchimp':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Subscribe to mailchimp newsletter form') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function subscribe_mailchimp_theme() {
  return [
    'subscribe_mailchimp' => [
      'variables' => [
        'webHookHash' => NULL,
        'content'     => NULL,
      ],
    ],
    'subscribe_mailchimp_block' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function subscribe_mailchimp_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'mailchimp_signup_subscribe_block') !== FALSE) {
    // Prepare Mailchimp Audiences.
    foreach (array_keys($form['mailchimp_lists']) as $key) {
      if (strpos($key, 'mailchimp_') !== FALSE) {
        $form['#mailchimp_checkbox_inputs'][$key] = [
          '#key' => $key,
        ];
      }
    }

    // Prepare text inputs.
    foreach ($form['mergevars'] as $key => $mergevar) {
      if (isset($mergevar['#type']) && in_array($mergevar['#type'], [
          'textfield',
          'email',
        ])) {

        $form['#mailchimp_text_inputs'][$key] = [
          '#type'     => ($mergevar['#type'] == 'textfield') ? 'text' : $mergevar['#type'],
          '#key'      => $key,
          '#required' => $mergevar['#required'],
        ];
      }
    }

    $form['#theme'] = ['subscribe_mailchimp_block'];
  }
}
