<?php

/**
 * @file
 * Contains node_terms_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function node_terms_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the node_terms_block module.
    case 'help.page.node_terms_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Show list existing terms on a given vocabulary') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function node_terms_block_theme() {
  return [
    'node_terms_block' => [
      'variables' => [
        'label' => NULL,
        'content' => NULL,
      ],
    ],
  ];
}
